name: Auto Commit

permissions:
  contents: write    # <--- fondamentale per permettere il push

on:
  schedule:
    # 10 commit al giorno, ogni 2 ore e 24 minuti (circa)
    - cron: "0 0 * * *"    # mezzanotte
    - cron: "24 2 * * *"   # 02:24
    - cron: "48 4 * * *"   # 04:48
    - cron: "12 7 * * *"   # 07:12
    - cron: "36 9 * * *"   # 09:36
    - cron: "0 12 * * *"   # 12:00
    - cron: "24 14 * * *"  # 14:24
    - cron: "48 16 * * *"  # 16:48
    - cron: "12 19 * * *"  # 19:12
    - cron: "36 21 * * *"  # 21:36
  workflow_dispatch: # permette anche l'avvio manuale


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # <--- garantisce i permessi
      - name: Modifica file
        run: echo "$(date)" >> log.txt
      - name: Commit e push
        run: |
          git config user.name "MircoNegriBot"
          git config user.email "you@example.com"
          git add .
          git commit -m "Aggiornamento automatico del log $(date)" || echo "Nessuna modifica da committare"
          git push
