name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # gira ogni giorno alle 00:00 UTC
  workflow_dispatch:       # puoi lanciarlo anche a mano

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # serve per poter pushare sul branch

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: mirconegri
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
