name: Visitor Counter

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # fondamentale per fare push
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate visitor counter SVG
        run: |
          mkdir -p dist
          FILE="dist/visitor-counter.svg"
          COUNT_FILE="visitor-count.txt"

          if [ ! -f "$COUNT_FILE" ]; then
            echo 0 > "$COUNT_FILE"
          fi

          COUNT=$(cat $COUNT_FILE)
          COUNT=$((COUNT+1))
          echo $COUNT > $COUNT_FILE

          echo "<svg xmlns='http://www.w3.org/2000/svg' width='200' height='50'>
          <rect width='200' height='50' fill='#4c1'/>
          <text x='100' y='30' font-size='20' fill='white' text-anchor='middle' font-family='Verdana'>Visits: $COUNT</text>
          </svg>" > $FILE

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
